[package]
name = "yew-app"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
js-sys = "0.3.59"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.32"
weblog = "0.3.0"
yew = "0.19.3"
