[package]
name = "paperz_integrity"
version = "0.1.0"
authors = ["Michael Hueschen <m@mhueschen.space>"]
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "0.0.19"
serde = "1"
